"""ZIP bundle builder.

Produces one of three layouts based on LabelSet type:

* ``yolo-detection``  → ``images/<split>/{name}``, ``labels/<split>/{name}.txt``,
                        ``classes.txt``, ``data.yaml``, ``manifest.json``
* ``yolo-segmentation``→ same as detection, polygons in label .txt
* ``classify-csv``    → ``data.csv``, ``classes.txt``, ``manifest.json``
                        (+ optional ``images/<split>/`` if ``includeImages``)

Image bytes are pulled lazily through the optional ``read_image_bytes``
provider so the ZIP can stream out without holding every image in RAM
at once.
"""
from __future__ import annotations

import io
import json
import re
import zipfile
from typing import Any, Awaitable, Callable

from .classificationCsv import classification_csv
from .classRemap import build_class_mapping
from .split import split_images
from .validation import format_for_labelset_type, validate_export
from .yoloFormats import yolo_detection_file, yolo_segmentation_file


ImageBytesProvider = Callable[[str], Awaitable[tuple[bytes, str] | None]]


_BAD_BASENAME_CHARS = re.compile(r"[^A-Za-z0-9._-]+")
_TRIM_UNDERSCORES = re.compile(r"^_+|_+$")


def _sanitize_basename(name: str) -> str:
    base = re.sub(r"^.*[\\/]", "", name)
    cleaned = _BAD_BASENAME_CHARS.sub("_", base)
    return cleaned or "image"


def _without_ext(name: str) -> str:
    i = name.rfind(".")
    return name[:i] if i >= 0 else name


def _safe_archive_name(name: str) -> str:
    cleaned = _BAD_BASENAME_CHARS.sub("_", name)
    cleaned = _TRIM_UNDERSCORES.sub("", cleaned)
    return cleaned or "labelset"


def _ensure_unique(name: str, taken: set[str]) -> str:
    if name not in taken:
        taken.add(name)
        return name
    base = _without_ext(name)
    ext = name[len(base):]
    i = 2
    while f"{base}_{i}{ext}" in taken:
        i += 1
    out = f"{base}_{i}{ext}"
    taken.add(out)
    return out


def _classes_txt(mapping: dict[str, Any]) -> str:
    return "\n".join(c["name"] for c in mapping["classes"]) + "\n"


def _data_yaml(
    mapping: dict[str, Any],
    has_splits: dict[str, bool],
    task: str,
) -> str:
    lines: list[str] = []
    lines.append("# Generated by videonizer export")
    lines.append(f"task: {task}")
    lines.append("path: .")
    if has_splits["train"]:
        lines.append("train: images/train")
    if has_splits["val"]:
        lines.append("val: images/val")
    if has_splits["test"]:
        lines.append("test: images/test")
    lines.append(f"nc: {len(mapping['classes'])}")
    lines.append("names:")
    for i, c in enumerate(mapping["classes"]):
        lines.append(f"  {i}: {json.dumps(c['name'])}")
    return "\n".join(lines) + "\n"


async def build_bundle(
    *,
    labelset: dict[str, Any],
    images: list[dict[str, Any]],
    annotations: list[dict[str, Any]],
    options: dict[str, Any],
    read_image_bytes: ImageBytesProvider | None = None,
) -> dict[str, Any]:
    """Return ``{"zip": <bytes>, "fileName": <str>, "report": <ValidationReport>}``.

    ``options`` keys:
      * ``split``           — SplitConfig dict
      * ``includeImages``   — bool; when True the archive carries image bytes
      * ``remapClassIds``   — bool; densify class indices
    """
    split_config = options.get("split") or {"mode": "none"}
    include_images = bool(options.get("includeImages"))
    remap = bool(options.get("remapClassIds"))

    fmt = format_for_labelset_type(labelset["type"])

    splits = split_images(
        [{"id": i["id"], "tags": i.get("tags", [])} for i in images],
        split_config,
    )

    report = validate_export(
        labelset=labelset,
        images=images,
        annotations=annotations,
        splits=splits,
    )

    class_mapping = build_class_mapping(
        labelset.get("classes", []), annotations, remap
    )

    excluded_set = set(labelset.get("excludedImageIds") or [])
    labeled_set = {a["imageId"] for a in annotations}

    def is_usable(iid: str) -> bool:
        return iid in labeled_set or iid in excluded_set

    taken_names: set[str] = set()
    file_name_by_id: dict[str, str] = {}
    split_by_id: dict[str, str] = {}
    manifest_entries: list[dict[str, Any]] = []

    for img in images:
        if not is_usable(img["id"]):
            continue
        s = splits.get(img["id"])
        if s is None:
            continue
        base = _sanitize_basename(img["fileName"]) or f"{img['id']}.{img['ext']}"
        if not re.search(r"\.[A-Za-z0-9]+$", base):
            base = f"{base}.{img['ext']}"
        unique = _ensure_unique(base, taken_names)
        file_name_by_id[img["id"]] = unique
        split_by_id[img["id"]] = s
        manifest_entries.append(
            {
                "imageId": img["id"],
                "originalFileName": img["fileName"],
                "archiveFileName": unique,
                "split": s,
            }
        )

    splits_present = {"train": False, "val": False, "test": False}
    for s in split_by_id.values():
        splits_present[s] = True

    # --- Build archive ---------------------------------------------------
    buf = io.BytesIO()
    # ``ZIP_DEFLATED`` matches what most consumers expect; the TS impl
    # produces stored-only ZIPs (no compression) which is wasteful for
    # text-heavy YOLO label dirs. The contract doesn't pin compression.
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        if include_images:
            if read_image_bytes is None:
                raise ValueError("includeImages=True requires read_image_bytes")
            for image_id, archive_name in file_name_by_id.items():
                s = split_by_id[image_id]
                got = await read_image_bytes(image_id)
                if got is None:
                    continue
                data, _ext = got
                zf.writestr(f"images/{s}/{archive_name}", data)

        if fmt in ("yolo-detection", "yolo-segmentation"):
            by_image: dict[str, list[dict[str, Any]]] = {}
            for a in annotations:
                by_image.setdefault(a["imageId"], []).append(a)
            for image_id, archive_name in file_name_by_id.items():
                s = split_by_id[image_id]
                items = by_image.get(image_id, [])
                lines: list[dict[str, Any]] = []
                for a in items:
                    if a["kind"] == "classify":
                        continue
                    idx = class_mapping["indexById"].get(a["classId"])
                    if idx is None:
                        continue
                    lines.append({"classIndex": idx, "shape": a["shape"]})
                text = (
                    yolo_detection_file(lines)
                    if fmt == "yolo-detection"
                    else yolo_segmentation_file(lines)
                )
                label_name = f"{_without_ext(archive_name)}.txt"
                zf.writestr(f"labels/{s}/{label_name}", text)
            zf.writestr("classes.txt", _classes_txt(class_mapping))
            zf.writestr(
                "data.yaml",
                _data_yaml(
                    class_mapping,
                    splits_present,
                    "detect" if fmt == "yolo-detection" else "segment",
                ),
            )
        else:
            # classify-csv
            rows: list[dict[str, Any]] = []
            include_split = (
                splits_present["train"]
                or splits_present["val"]
                or splits_present["test"]
            )
            only_one_split = (
                sum(int(v) for v in splits_present.values()) <= 1
            )
            for a in annotations:
                if a.get("kind") != "classify":
                    continue
                archive_name = file_name_by_id.get(a["imageId"])
                if archive_name is None:
                    continue
                idx = class_mapping["indexById"].get(a["classId"])
                if idx is None:
                    continue
                cls = class_mapping["classes"][idx]
                s = split_by_id.get(a["imageId"])
                file_in_archive = (
                    f"images/{s}/{archive_name}" if include_images else archive_name
                )
                rows.append(
                    {
                        "fileName": file_in_archive,
                        "className": cls["name"],
                        "classIndex": idx,
                        "split": s,
                    }
                )
            zf.writestr(
                "data.csv",
                classification_csv(
                    rows, include_split=include_split and not only_one_split
                ),
            )
            zf.writestr("classes.txt", _classes_txt(class_mapping))

        manifest = {
            "version": 1,
            "labelSet": {
                "id": labelset["id"],
                "name": labelset["name"],
                "type": labelset["type"],
            },
            "format": fmt,
            "options": {
                "split": split_config,
                "includeImages": include_images,
                "remapClassIds": remap,
            },
            "classes": [
                {
                    "index": i,
                    "id": c["id"],
                    "name": c["name"],
                    "color": c.get("color"),
                }
                for i, c in enumerate(class_mapping["classes"])
            ],
            "images": manifest_entries,
        }
        zf.writestr("manifest.json", json.dumps(manifest, indent=2, ensure_ascii=False))

    return {
        "zip": buf.getvalue(),
        "fileName": f"{_safe_archive_name(labelset['name'])}-{fmt}.zip",
        "report": report,
    }
